services:
  # app:
  #   container_name: server_prueba
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   restart: always
  #   ports:
  #     - "${PORT:-3000}:3000"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - PORT=${PORT}
  #   depends_on:
  #     - products-db
  products-db:
    container_name: products_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

 